services:
  git3:
    image: ghcr.io/0xa1bed0/git3:latest
    container_name: git3
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./vault:/vault
    environment:
      - ACCESS_KEY=anatolii
      - SECRET_KEY=your-secret-key-here
      - BUCKET=vault
      - REGION=us-east-1
      - GIT_REPO=https://github.com/you/obsidian-vault.git
      - GIT_TOKEN=ghp_your-personal-access-token
      - GIT_BRANCH=main
      - DEBOUNCE=10
